table Neg
	lineageTag: 97803c21-17f9-44ff-984c-5845b9147e65

	column go_lk_originatingleadid
		dataType: string
		lineageTag: 71a5276b-5a4a-4e05-b875-3dedb9eba108
		summarizeBy: none
		sourceColumn: go_lk_originatingleadid

		annotation SummarizationSetBy = Automatic

	column go_st_codnegociacao
		dataType: string
		lineageTag: a61eae05-7140-4a81-8700-541f0205886b
		summarizeBy: none
		sourceColumn: go_st_codnegociacao

		annotation SummarizationSetBy = Automatic

	column go_st_codnegociacaosctv
		dataType: int64
		formatString: 0
		lineageTag: 8df97313-c9c0-4530-bff9-598ab490d39c
		summarizeBy: sum
		sourceColumn: go_st_codnegociacaosctv

		annotation SummarizationSetBy = Automatic

	column go_mn_valornegociado
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f4c5cc8e-3774-4179-a4a7-cda8e92de062
		summarizeBy: sum
		sourceColumn: go_mn_valornegociado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column go_lk_empresafaturamentoid
		dataType: string
		lineageTag: b753edd8-7b04-4dfc-86c1-9a3959c7e50a
		summarizeBy: none
		sourceColumn: go_lk_empresafaturamentoid

		annotation SummarizationSetBy = Automatic

	column OpportunityId
		dataType: string
		lineageTag: fdc3ba5b-0eee-4601-ae6c-08a10d57e0ee
		summarizeBy: none
		sourceColumn: OpportunityId

		annotation SummarizationSetBy = Automatic

	column statuscodename
		dataType: string
		lineageTag: 8360ac71-ff7b-4294-8e02-01879c8ae34a
		summarizeBy: none
		sourceColumn: statuscodename

		annotation SummarizationSetBy = Automatic

	column Thermometer_cod
		dataType: int64
		formatString: 0
		lineageTag: 4d4c43fd-7f94-4ea3-8848-02a0cd10d637
		summarizeBy: sum
		sourceColumn: Thermometer_cod

		annotation SummarizationSetBy = Automatic

	column Thermometer
		dataType: string
		lineageTag: 04794635-d789-4316-b473-a61c14adfd75
		summarizeBy: none
		sourceColumn: Thermometer

		annotation SummarizationSetBy = Automatic

	column TipoMidia
		dataType: string
		lineageTag: ff61f0fc-aae0-4cbc-888a-33f91bbf913d
		summarizeBy: none
		sourceColumn: TipoMidia

		annotation SummarizationSetBy = Automatic

	column TipoMidiaCod
		dataType: string
		lineageTag: 9cf0f364-2ecb-4343-88e2-337e09346a53
		summarizeBy: none
		sourceColumn: TipoMidiaCod

		annotation SummarizationSetBy = Automatic

	column 'Data de Integração_Final'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 371dadd2-2009-4cfe-b0b2-4809fee19ae2
		summarizeBy: none
		sourceColumn: Data de Integração_Final

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column URL
		dataType: string
		lineageTag: ed3fdb35-2de7-4c80-8341-ae9fdbdd288e
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column Estado =

			SWITCH( TRUE()
			    , Neg[statuscodename] in {"Perdida"}  , "Perdida"
			    , Neg[statuscodename] in {"Erro Durante a Integração (Aprovada)", "Integrada no SCTV (Fechada)"}  , "Ganho"
			    , "Em andamento"
			)
		lineageTag: b53c0570-2b41-41db-b903-8e00f56ee5c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Motivo Opt Perdida' = IF.EAGER(Neg[Estado] = "Perdida", 'Neg'[statuscodename], BLANK())
		lineageTag: 894bb1b3-6393-4b77-a44b-f9ce29e4d10b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Briefing Opt' =

			CONCATENATEX(FILTER(ALL(Briefings), Briefings[go_lk_oportunidadedeorigemid] = Neg[OpportunityId]), Briefings[go_name],", ")
		lineageTag: 6c101a0d-1944-4136-bd7d-8f8aaf21ee7e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Neg-f104d4b0-c0ef-4b84-8505-057fa867a586 = m
		mode: import
		queryGroup: Dynamics
		source =
				let
				    SQL = "SELECT
				            OPT.go_lk_originatingleadid,
				            OPT.go_st_codnegociacao,
				            TRY_CAST(REPLACE(OPT.go_st_codnegociacaosctv, '.', '') AS bigint) AS go_st_codnegociacaosctv,
				            OPT.go_mn_valornegociado,
				            OPT.go_lk_empresafaturamentoid,
				            OPT.go_opportunityid                AS OpportunityId,
				            OPT.statuscodename,
				            OPT.go_pl_winchancethermometer      AS Thermometer_cod,
				            OPT.go_pl_winchancethermometername  AS Thermometer,
				            Midia.go_name                       AS TipoMidia,
				            Midia.go_st_codigo                  AS TipoMidiaCod,
				            Integracao.DataIntegracao           AS [Data de Integração_Final]
				        FROM go_opportunity OPT
				        LEFT JOIN go_tipomidia Midia
				            ON Midia.go_tipomidiaid = OPT.go_lk_tipomidiaid
				        LEFT JOIN (
				            SELECT
				                go_st_codnegociacao,
				                MIN(CAST(DATEADD(hour, -3, go_dt_dataintegracao) AS date)) AS DataIntegracao
				            FROM go_opportunity
				            WHERE go_dt_dataintegracao IS NOT NULL
				            GROUP BY go_st_codnegociacao
				        ) Integracao
				            ON Integracao.go_st_codnegociacao = OPT.go_st_codnegociacao
				        WHERE
				            OPT.go_lk_originatingleadid IS NOT NULL
				            AND OPT.go_st_codnegociacao NOT LIKE '%SF-%'
				            AND OPT.statuscodename NOT IN ('Versionada', 'Versionamento Cancelado', 'Versionamento Reprovado')
				            AND NOT EXISTS (
				                SELECT 1
				                FROM go_opportunity X
				                WHERE X.go_st_codnegociacao = OPT.go_st_codnegociacao
				                    AND X.statuscodename = 'Integrada no SCTV (Fechada)'
				                    AND X.go_int_versao < OPT.go_int_versao
				            )",
				    Source = Sql.Database(OrgDynamics, BD_Dynamics, [Query = SQL]),
				    #"URL da Oportunidade" = Table.AddColumn(Source, "URL", each Link & [OpportunityId], type text),
				    #"Uma linha por Lead" = Table.Distinct(#"URL da Oportunidade", {"go_lk_originatingleadid"})
				in
				    #"Uma linha por Lead"

	annotation PBI_ResultType = Table
