table Status_Agregado
	lineageTag: 363e932b-1925-4c7b-b98f-b706ee9f2270

	column Status_name
		dataType: string
		lineageTag: dbb3deec-a75b-43c4-b16e-15ba8d670a47
		summarizeBy: none
		sourceColumn: Status_name
		sortByColumn: id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: cccce95e-316a-4a17-b00a-aaac31ef6de2
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	partition Status_Agregado-422c0714-ad41-415d-9b51-a3ef222070ec = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs1VSMxLScxNzSvJV9DwSU1M0VTSUTJUitWJVgpILUrJTEESNgILB5Ym5mSmZSYnIksZg6VcUosLscmagGVR7fIvKAFJmaJaBRU1w7QJKmOO1SKopAVY0j0xLyMRLmapFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Status_name = _t, id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Status_name", type text}, {"id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

