table Termometro
	lineageTag: f781109f-6029-41da-9d6c-34e5fcf2bced

	column Termometro
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: e9f6d6bc-6bd8-484a-b6ad-37e44b8d6f21
		summarizeBy: none
		sourceColumn: Termometro
		sortByColumn: ID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: f373f2f3-fdb0-4ebe-8857-fd6d9c0c8dbd
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition Termometro-d5416508-b679-4d32-8be0-c417a9f8c5f9 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjQwUFXSUTJRitWJVrK0BLGNwWxzsLgRmG0KZhsqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Termometro = _t, ID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Termometro", Percentage.Type}, {"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

