table pbi_dim_campaigns
	lineageTag: 'tbl-dim-campaigns'

	column cd_campaign
		dataType: string
		isKey
		isNullable: false
		lineageTag: 'col-cam-key'
		summarizeBy: none
		sourceColumn: cd_campaign

		changedProperty = IsHidden

	column nm_campaign
		dataType: string
		lineageTag: 'col-cam-name'
		summarizeBy: none
		sourceColumn: nm_campaign

		changedProperty = IsHidden

	column dt_init
		dataType: dateTime
		formatString: Long Date
		lineageTag: bcbc1589-ffd9-4525-81bd-b986fd257eba
		summarizeBy: none
		sourceColumn: dt_init

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_end
		dataType: dateTime
		formatString: Long Date
		lineageTag: d137814a-69eb-4ccf-9e02-e175e3a0f0c6
		summarizeBy: none
		sourceColumn: dt_end

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column vl_budget
		dataType: double
		lineageTag: d861b7b4-cf35-4459-a12e-125318d32f15
		summarizeBy: sum
		sourceColumn: vl_budget

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pc_discount
		dataType: double
		lineageTag: 0079d70e-2cb9-48ed-9f9c-338829d45b9b
		summarizeBy: sum
		sourceColumn: pc_discount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cd_account_client
		dataType: string
		isHidden
		lineageTag: 7dce275e-a139-4e8b-bc3b-a80ef4b14a33
		summarizeBy: none
		sourceColumn: cd_account_client

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_account_agency
		dataType: string
		isHidden
		lineageTag: e99fb00b-b2ed-4b6a-8466-8317eb65d601
		summarizeBy: none
		sourceColumn: cd_account_agency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_negotiation
		dataType: string
		isHidden
		lineageTag: af3fd424-8a56-40cf-accd-5ca03f5dfc55
		summarizeBy: none
		sourceColumn: cd_negotiation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_target
		dataType: string
		isHidden
		lineageTag: 74a6b482-6352-4737-a9e3-974055e51f48
		summarizeBy: none
		sourceColumn: cd_target

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_list_channel
		dataType: string
		isHidden
		lineageTag: c851962d-7ab9-451f-9132-28ac89769cf4
		summarizeBy: none
		sourceColumn: cd_list_channel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_ad_type
		dataType: string
		isHidden
		lineageTag: 2bec18f8-652c-46e4-b933-8de1056ff813
		summarizeBy: none
		sourceColumn: cd_ad_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cd_payment_type
		dataType: string
		lineageTag: da463d20-7800-4aca-9082-9edd9453c007
		summarizeBy: none
		sourceColumn: cd_payment_type

		annotation SummarizationSetBy = Automatic

	partition pbi_dim_campaigns-partition = m
		mode: import
		source =
				let
				    SQL = "SELECT * FROM medialivre.pbi_out.pbi_dim_campaigns",
				    pbi_dim_campaigns = fx_dbricks(SQL),
				    #"JSON Channel" = Table.TransformColumns(pbi_dim_campaigns, {"cd_list_channel", each Json.Document(_){0}, type text})
				in
				    #"JSON Channel"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

