table Anunciante
	lineageTag: 13a9293c-7f1e-4f15-b2ee-c9a5046012b1

	column entId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4f71e52a-0de9-41db-b243-f953e1f14b51
		summarizeBy: none
		sourceColumn: entId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Anunciante
		dataType: string
		lineageTag: 0f83d09d-b0d8-4e37-b256-c5dd17bffda0
		summarizeBy: none
		sourceColumn: Anunciante

		annotation SummarizationSetBy = Automatic

	column 'Anunciante C/ Encomendas' =
			
			VAR _1 =
			CALCULATE(
			    YEAR( MAX( Encomendas[Data Exibição] ) )
			    ,FILTER(
			        ALL( Encomendas )
			        ,Encomendas[anuncianteId] = Anunciante[entId]
			    )
			)
			
			VAR _11 =
			CALCULATE(
			    YEAR( MAX( Propostas[proDataCria] ) )
			    ,FILTER(
			        ALL( Propostas )
			        ,Propostas[proANId] = Anunciante[entId]
			    )
			)
			
			VAR _2 =
			IF( _1 = BLANK() && _11 = BLANK(), 0, _1+_11 )
			RETURN
			IF( _2 = 0, "OUTROS", Anunciante[Anunciante] )
		isHidden
		lineageTag: e8dc8584-39f9-459a-8108-061720d6c2ba
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Anunciante-05f4ec63-e93e-4ca0-9acc-25a0c1ea37a5 = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)    entidades.entNome,#(lf)    entidades.entId#(lf)From#(lf)    entidades"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"entNome", "Anunciante"}})
				in
				    #"Renamed Columns"

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Anunciante/Source.{entNome,0}","Section1/Anunciante/Source.{entId,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/Anunciante/Source.{entNome,0}","Section1/Anunciante/Source.{entId,1}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

