table Bonus
	lineageTag: 69940185-b820-4549-8437-f3e91a92c516

	column bonId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 53771da5-e8b0-4c57-aba3-770b57f41dc7
		summarizeBy: none
		sourceColumn: bonId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Bonus
		dataType: string
		lineageTag: ddcf93a3-c359-4d33-8aca-c96439fbccf8
		summarizeBy: none
		sourceColumn: Bonus

		annotation SummarizationSetBy = Automatic

	partition Bonus-304d02b7-eb22-4915-b4be-0869f4c0cb47 = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)bonId,#(lf)bonDescricao#(lf)From#(lf)Bonus"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"bonDescricao", "Bonus"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

