table Produtos
	lineageTag: 6b9535bb-824f-4d66-b61a-50bef6c3b81c

	column proId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 14317b1c-2943-4346-afad-a4a5de72af4d
		summarizeBy: none
		sourceColumn: proId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 68b1c19e-69ad-4f1f-a0ca-d3272b8370c1
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column TipProId
		dataType: string
		isHidden
		lineageTag: a925b872-b036-411f-bd6d-442b6c99df20
		summarizeBy: none
		sourceColumn: TipProId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Produtos-4e7638eb-fbb2-450c-a360-7c64eed6d83b = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)proId,#(lf)proDescricao,#(lf)TipProId#(lf)    --tp.tipProId,#(lf)    --t.tipProDescricao as [Setor Atividade],#(lf)    --tp.tipProDescricao as [Sub-Setor]#(lf)From#(lf)    --tipoProduto t join tipoproduto tp on tp.tippropaiid = t.tipproid#(lf)Produtos"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"proDescricao", "Produto"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

