table CentroCusto
	lineageTag: ae156cce-08c2-44ee-ad84-c9ad6f7e69ba

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 39a40ab5-9b60-43bc-aee1-cde9f6f8f9da
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: ac95f79c-bc90-4db8-8543-2f4f054bbd39
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column TipoActividadeApurada
		dataType: int64
		formatString: 0
		lineageTag: db6123aa-3a47-4281-b362-f14ea21725b4
		summarizeBy: sum
		sourceColumn: TipoActividadeApurada

		annotation SummarizationSetBy = Automatic

	column codigo
		dataType: string
		lineageTag: 08afd341-0bdf-42da-850e-9e784bbbe65e
		summarizeBy: none
		sourceColumn: codigo

		annotation SummarizationSetBy = Automatic

	column 'Ativ. Apurada (CC)' = ```
			SWITCH(
			    TRUE(), 
			    CentroCusto[TipoActividadeApurada] = 0, "Nenhuma",
			    CentroCusto[TipoActividadeApurada] = 1, "Meios", 
			    CentroCusto[TipoActividadeApurada] = 2, "Pessoas", 
			    "Não Definido"
			    )
			```
		lineageTag: c8c7c851-0d14-4213-95d6-0b5a525d6203
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Código Conta' =
			
			IF(
				ISERROR( VALUE( CentroCusto[codigo] ) ),
				CentroCusto[codigo],
				CONCATENATE( VALUE(CentroCusto[codigo]), "" )
			)
		lineageTag: be2582a6-6fcd-4fb9-8965-4f32cb75d4a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: 929fe862-2942-4b80-8ada-90608779b05b
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column SubGrupo
		dataType: string
		lineageTag: c80733b5-3763-4751-992a-ecd099feccc8
		summarizeBy: none
		sourceColumn: SubGrupo

		annotation SummarizationSetBy = Automatic

	partition CentroCusto-29371f68-850c-4871-83ed-57f127848dde = m
		mode: import
		source =
				let
				    Source = Sql.Database(Org, BD, [Query="#(lf)Select#(lf)cc.Id,#(lf)    cc.Nome,#(lf)cc.TipoActividadeApurada,#(lf)cc.codigo#(lf)From#(lf)    Centros_Custo as cc"]),
				    #"Merged Queries" = Table.NestedJoin(Source, {"codigo"}, CentroCustoAgrupador, {"Cod_CC"}, "CentroCustoAgrupador", JoinKind.LeftOuter),
				    #"Expanded CentroCustoAgrupador" = Table.ExpandTableColumn(#"Merged Queries", "CentroCustoAgrupador", {"Grupo", "SubGrupo"}, {"Grupo", "SubGrupo"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded CentroCustoAgrupador",null,"Por Agrupar (CC)",Replacer.ReplaceValue,{"Grupo"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Por Agrupar (CC)",Replacer.ReplaceValue,{"SubGrupo"})
				in
				    #"Replaced Value1"

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/CentroCusto/Source.{Id,0}","Section1/CentroCusto/Source.{Nome,1}","Section1/CentroCusto/Source.{TipoActividadeApurada,2}","Section1/CentroCusto/Source.{codigo,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/CentroCusto/Source.{Id,0}","Section1/CentroCusto/Source.{Nome,1}","Section1/CentroCusto/Source.{TipoActividadeApurada,2}","Section1/CentroCusto/Source.{codigo,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Exception

