table TiposHorario
	lineageTag: cfffe5a1-3585-4bf0-b59c-8d50c3f59fb6

	column Tipo
		dataType: string
		lineageTag: 4d3cc5d0-e595-467c-84ac-e5bb9f8579f1
		summarizeBy: none
		sourceColumn: Tipo
		sortByColumn: Id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: b3781202-ffbc-4c15-bf0d-30cf9953edac
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	partition TiposHorario-caf0f259-fbc9-4ecb-b60d-60f70895ac66 = m
		mode: import
		queryGroup: Agrupadores
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci1OTsxJVNJRMlaK1YlWcizJLMtMSUxJBYqYgEVcK1KTSw8vP7w4HyhkChYKyM8rAfHMwDznxILEZJgeQ7CQX2pyanExWKwYKGikFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tipo = _t, Id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Tipo", type text}, {"Id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

