table RLSFILTER
	isHidden
	lineageTag: 147ba4d8-fce8-4b61-bf47-535546858ae5

	column domainname
		dataType: string
		lineageTag: 7e17705b-05e5-43e6-9cc0-cb6f007dc17a
		summarizeBy: none
		sourceColumn: domainname

		annotation SummarizationSetBy = Automatic

	column positionid
		dataType: string
		lineageTag: e5bfa886-1154-4092-9c39-811c1ef80cbf
		summarizeBy: none
		sourceColumn: positionid

		annotation SummarizationSetBy = Automatic

	column PortalsAzureID
		dataType: string
		lineageTag: daa93992-0b55-4a5c-946b-21e8eb0d8ca9
		summarizeBy: none
		sourceColumn: PortalsAzureID

		annotation SummarizationSetBy = Automatic

	column systemuserid
		dataType: string
		lineageTag: c32d8bfd-80cd-403a-bd65-79c63d92c8d7
		summarizeBy: none
		sourceColumn: systemuserid

		annotation SummarizationSetBy = Automatic

	partition RLSFILTER-2688d5d8-d176-417c-ac89-074faffa1b61 = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"GetCDST_EntityTable"("SystemUser"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"azureactivedirectoryobjectid", "domainname", "positionid", "systemuserid"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"azureactivedirectoryobjectid", "PortalsAzureID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

