table Icones
	lineageTag: 54715cfa-1f4d-4650-bfdf-53e0f149d55c

	column Cod
		dataType: string
		lineageTag: 873e3120-2e27-47b0-86f3-dd7ef32a7575
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Cod

		annotation SummarizationSetBy = Automatic

	column Descricao
		dataType: string
		lineageTag: bf7b78d2-f8ea-4845-9b8f-6cb506cce8e9
		summarizeBy: none
		sourceColumn: Descricao

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 2263e7fa-8671-45a2-990f-f1dc7e3a0de8
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Icones-bd1cfcb5-95bd-42f7-aa12-d2633cabd908 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("7bvHzvNMn+Z3Ko1vyzaY0wxmUQxiJsUcBr1gFnMmJZ6OFwYG8Em4T8x83h57AKM3/tYvgfuWqECxqv51XdevKP33//6PIt3T/9IMaV3C81j/1yzdSor41ybgLOdCNKmewLOZrv8R/fq5J/3Z5WoexM+t0AxyTjx3VBTpRTtwiOjAipT65oETyeg93QXsYn2hNpl34vf8Zd1WDL/ap1YzWzNr5xXXtnf9zF3ZxPdUJ4wCpmk3fFmzJ8227y+gEvdy2cb1/Z50paEGjGYEqYOtuIXrA96bqUbbwl5IGZSsxf2Bj5gkh5tm7yxHaNcUipvt5xXGoZtle/reydVggsj7RvU4Lu8xMIzJKKp66PT4TTOQWxnjc646AKWB5SBRPyQQ+d8QZkYElOs2rmf/bazgeF27SbMQsbOvdj0OanzZQlQkOdmOxqcGR1K6vmM6IQ0Q6Q3kWru4TM6zZFoDeJu0OwjxzVJU1ErglYL2+GKweYiGFN37qAVv0nK4UycrXZpS6dOl44XlH/m+wDSnZE02h5qK/snZwqUqHF0VcIUqGzF/FkDgY5k2OqV+pAKZNs2EFZUQfUDheFURvKL1RoCRNveT0nv54vIRhwkaOIG+8FV1SYTr26XwaqAJ00MQujfmGW6TO+/Gao220VcmR8BYR1dZwPhIG0nT+mDwr2H06y4bqsHFvuGlJTuQhAEizhdxRsLFmKREUxt4A4b+GqDaZGPDEPFd+BjIng/l9IqlS5H29g2AoUcl3ICt8AIkYrG1kGuNgn/OwRZqHBAWV1coW+FY3FgDQzWSvz4V+VbVt9rg1YHLHSFw0AcYn2GDjfyLD8ZQMJnTg/sykup3RD8o63N6hYvvPqG1bFOjj/V+lzEdvZlJkwYcLJz+0iNeS1UyRAz0QoBE0JKOfKukEDdll+N2fvtbzWEiKydKo3LUF8SXpr6ab4awcAX3cf2zE6QSoHDRwxf5nuFKpmyotsEW6lx9H3eykeyH3C3eEvDyVwtx1FxhQFBGq99lWmA8sD6e2+LcLRU4dXyJ8wOD+Kf+3h8psKh+/F6875/5xUA5lTtaUF5yrrhqRaUuJNuvK6py/ou/IIQYhMVEM32u3j8o+IXssRfsMxwGm/EWX93ytzmYuC13CIpXmVgP+UNUEOLDEAbcppcHffDopDWtFQfyBzg8uTpEiQG+6e+nar/s9pVM9vaUlzZnOs/iyO1gM7XbRj0nHsXdxpmG/gafX5Pzv7juqsNg0ggdzDpQ6bGKDwXdqobr9TpF15W+8xVzPNA1gU728dIXuIFzsFIF9xRrL9sViqxjbb9+qYvsvauXnlpAJmXHgMQsK/QSy78MUtK7IM2WAjLHcui2vDBO5y4i1xO4wlko4+XR5iDdVaJPgDuG9U2kY9y5BASd/0bj4VKut8WkxDjtLVjMPZZq2W+2NtkOTI59ZNmTMs0uGqBXngXhcdBWrdW9ub7uFx1fvu0ABRSoIzuqMK77xBnqaXGJoJMzLbxMOG14jUtpuHwG1PDMFNFtfkQVLIWsOraXWoGR15JlI54HNgNKksI/RB1+rAVKm9+ix7wS7a9Uxx4JUE9z7epOHCFEiSj/oPhl/MB+OMEr1pQoMAs0eyqWfMapfoMAvDlULLoLPZXuT/+/w/nOfEg8fuAGci86Al0KCpdgQVKTayndMBR/3VpQNI1Hz0lUGGs6DzOtrYKkf1Lzwn6qfBm1Nlf6/NTX4WAmkH9pIxMJoPnR1gIXSrwTotmFM4Qt0sfXeJ5KgUgDT5OlI5E7J4FWTLrdMdOjERhBUATasVzNqflSTfUe3d23zCjSJcTOEqLG+K5tduom6bKu+eJB5KpuyNSMmIN1Hyle0lAXB8FnJ5pOwgOOI/qpbXGI8Y1nnm6NsTBObU7i5aTioudAaZdtT0mz4AvM9v2GWo2+ai/HopZtsDF4DQndF9c9gZKUoQGnDATHqnoIzZh5LHxO20hk2AJVsxk1ivEeK9Xe8oHDXUJt/88GfsmRjLi98B4leqcxqDlIcyWkYnNXZkRI/WmuvUXJ67T952hBSrHzb8RF0L/0KrZSaaFbfuJUFFjBr/SRo4d3ciKKC5YtZIyDZC/h48shCIEugKLXs/jeciZgaLH5+2R0+pAGek9TfcAvrLRC7v7OWIviUfO0tme6cq4L932gZs+UDlaHb3CgL1mALfvv7rmt+J4fQ+BfDAfUUm2MXg3oc9lt/vZOemZMPPpuLyfi0P17wr29iFfGQlBVxhHJxODmy5KkUcNRrRCJfU7N1QLRzDSlLa/a7yCV5UPOb2b2gDhidbvUYOnzKaoKCD5+yOMx93BL9g8q89h+/BS86k1ZkjEtEH7ZcdtFXMTUL3s6NwO8+bxRv47HPKPPKnEQfnc/nX2th9GqgrG25uNR5G5yu77NIzgZBvMpQIYxDZWIo6Q143ZN8zEjMjPNzlI2xEvwiAgVERRGOaOsN8fBkl9ZNx2LtvXL2gD9eN84xPuKGp8OHld/SMtXMPctjDPnKxHRNvxh4VJtxmAYH/VEASVxBsjaw9jwNVhRmOFBJgT8pAYJlAZg5O9GcEyGBb/gsp0htItr++kJSYjvGCVcad+d+TXM/igsXwQkQ7LBHsp5VPgjuBt8Xf3n86eX2dJ010epasp7v5W4wkn/EdmUohPXknP+4sPmJHxWfzyoVvvPzHYvBKITU0IEQ1Tm2SUbcl+P9jDNUxAWAHGtMmi/K3PQwnZr/pDlxz+CkI3b4mMBC4m6oaMW3BPBhie+lvnsPU90NMRAJxrFStM+4TYg2JfxWKqrJZat7yo5IeWLW/jVza4RLtaE71L7NQr+3OvaqDziWK43IE0OzhtHYQ5hbEVPUvhHTmqiFOcqYllv36lyr1aMfc834KHIXfw3Wb3J0X+1lD2DIqJr0ArqqVU0FHKcmc7Zvbi7/k31BUkkZ/tpzMZF6MUbJDQnoEkq5hg4hew5zhaZiOr9oMN0BflKRXqUWsYng8f8atrbrJdzs4M7B/pUjwwEI5H8seqAf1rR0nxSoDByGCis39IzJRcLqkMEGNqZmFOjlB7sIgF/D4GxKn1we8n2cl9puNdOaIQCR/XdtydORbxepsl/B87n0EGemho8OckcEuyzGn6ciIUFceAqD4xmYZiQrq9XYSsQY6FIuli8OvF8fJHqMG0Q9LnrUD7kURo+s6waYrEWAoKzDgqlW0shSRObUQWvlfgTLl92LLGyJw3xxYQYw8WEkUpcTWhJoEV2VPPMj9HEFuzbEruOf+Mosr0OdmZhVzckLfFrrgV4UrDIKuceKTj8KSzix5YuDvIQ948/j3aIIj5FjkBMBW+pvCGwlyRS/DWTWCfLlvwLAd0G5Xv0JkSCcdoc77DN+aI/MPICww7Wd578AiD+VuMNhR9P4o2lSERTHtwl+uU8FRk03Hj7kDApAjx3AyJhoBu0JxuWFnTbWscl5b/tHmDSUlKeuAfoJ2S/sqkvwUiLnEw2QpAEFbYIytOecP6EibcMJ/SDORUz9bEGrV8SYxZDQzObc8DX5ijvPcKbSY1jMv2yqPsDUMD1A8vRSD5WlP/2j3/9x7ZP83PjlsO/OMe4/UvRbPM0/vv/eZbN9o9/+9f/35Qm/kVp4D8ojV/SSC7/3BnE/4fS0IyIRt8AX3Z4lBBIoWDU8s4diNhzUgzE5AGtScRBvEukrU41qqlfvsqZnm2yccUSCSbnnwcjKTaX+fjN1P6aO3zb2/dt5uCsVYKHeL2Rro2gIkz3hpOP+SG1PQBRPLG0lPZTCl/5fX9q+aSThWttdsHMGIv4bvVMIxpMt8/9+eUThJn/oq6oubuLn+mlkVLrMD052iL501gH3Vxg2vzvdXEDXHv1awMvMQ5Mbw3MoGL4R7Yv9afAMWIMQHhy6DuOxAANU1jUm+V8cAlkoj3UBY9IhEzt35qRuC8nktYEA7Ul++kDrbLcx+Tus5ml4CISX8b1dt7e1wMCobtaMUBsXqtDldYsscRbBBZLOdWnuizo8OtyDUJSweXYyJ+4/NLfYe/jAfYd7RHFCP76+YzT1kbI0feZpCS+zFe6ILghIDUi2yBq+o7Fn3Zv1NhadYtHB5gqDMRFY4sUJllVXiekzhIszLKd8TOR8SuCAy8YjnrGUrbdKOrkFTYegmFACKKSO6oNLBfzvIZta8GXEonsiq2yAKzq7J3fihAllhySmC9fKEB1NGe44b1FrhgRqBUMxpMSGxE9YnHvaioEo42D5WGI1X96UzafYxo1wz5BSJGUvlqHNnnIi+uutQCQ0/V4XTb8t5z578W9YY+mzcdgRHcphTROS/F7mLUgcwvdQ8gGPtaqmtgByQALNtFDOIsns+I4OPmTq3v1yOu69HEjdrsemGEKqZpKB0/YVdlP0Czr4nTOEQwVy47LoV1RGf466t5rnn/sAcD1rTe/4+U4g/AJLxxfW/V6UREdEcmC9NtTEEAj3sF0vIVWEEJCrsVP/jHMlGJWvLyhlxnDbDnxhy23BWw8sELNa1BcaaykX6bWzfES2ExZ2QpiCSv8a+5zquOT4tqpdV3/tz+zP0/7cizS9X97Znn57INhWvfmTv/9//j3/336l6Ect7T/Z1RA+bPL/08VEIT3IOvPnXf0v1Sg4Ik/azUjBD8win1zJZVeH6wYyZtdmtppxBqkdoDXXTzWyXTHQ2h6YgN6l4s6ZAf+6wsm33fFuPMTUXzZjwrrvET8NP79Aal/nkf2zuY0eOZIUsz3flfwO7IYFCu+9PjsjreOq0lbJTlMjwVM0vc6wpDN8uzpIlzGj3sO+Z/rAm+b4gUAEiCvOWixo/rEnFELyFr7EndVIwmbpDYH2gq7yyuaMNA0vT5kQxA3xNMHxy7hNEUjSj0Tov3wYynnR48ecqPGxJj86fyA+lntREkHy01ayQHgrH4kMlRMD+QYpQsWJbUw5fX2J26E0HnSRYgjHmrhDylEDpPJ34c3ceDQi1nc4sNmdCeIDLSRQzKeyGuGzdoEPToD54RyKzIw0PFQHU/s6woorVamOSPeQGXXz8AOZ4+ucNUdsm3dqDUlgGsMeJ6/2vbNn2OddO3bLLhAY9WYI9jpH9xdHu6o6wtEocIp7WSLDgIoofBTN79f+PbhT0fkXpxW2Y9CD+0Ev3AzMkv2G0k5D+OIG76ztS6ARFkwuZVlAzQWKHwmZtLe5beR0l74YxVi69CeHibwpL7rKuGFhpiKheUDZ8zjFi7S9IIA050ZIZ/g1KHZQRES4OSiUZqiPUCWmQdkSZhlJiGeXmI90dC5YowvlmUiLW+OHbnIIaSDizk3bX3ACepvqHpqrYJ+tMG8RBgt1hzXVuTs7QfXiEZmYnQ+9o68N3sUXBpodIpr1BJLSVuCUwrNop28BKdV2QIFXJ1IxSAPeQ4ewwZrcQR+KqxA4/1u/0G+GC8GCu17QCSG/hymKAIAPl/WLPNdMpv40IEeHA8xFOF6RcqpbeDp7EgpNe0Jv3fzte+VddLoiwzt7zMXF/J8ZCy9tl/1RiGIsCuWniHSgtuQtLzO1wuxTgkOcNJuG+46fWp2PbbjYbcRaz7EJ8da7QL1hMPlKfdto3/OR/49aLtzM5D+LCzaOpdGIRkHVN6VyUoaKY6yLwXoHVItwBFQSoWHVmapI37DQmFycWFab5tXKEEVT57c7DusK6LfMRbSmiivs5dhAl5LG+Lz64bio5jZ5f081HeFADw1FNkKwGHv3CGOMt7Gb63ClOA/kvsbUPDkQMqEey1MoCjcC07h5/SFRIKeIwADibITcct11Dxqn0fJ8UK8eq5WZ87nK7+bf3CpUiwD57L/3V9i3YM/xdy5jBXHHEKC/hmbes8I1PW05Keq0iMOThdbCkd2k/Tys+xH2kDhlkD4CYRqEk8BOSWKR1HoJGijipFxG85PaAxfnORLM5/CqJMwKWl6Pbjt+JlDs8NfkR8ZTlFrEcD5W7iI/XcUV5N7doN+fuyjqhKFej9evEkN1N8NscWfT5Y3c2WkWAI/RUOTdLTZRsAmGJrlrN8G2GAb3PVhb/2bd79u7pPxtd8sBxqnUeWHcY4vemj+T24G5ZFtIa6nmuvOGLQ9s6ss+LDD3V0Xcpqn19/k41zBcuhnxLMYKwLDbFZvIKLiad/z7nUsHlcWw/eSDnMRmm1Mvndkpsv7mwN2f/iAxoebZOFGaOOiwF/R2pZk+BHfAlBqT0mTT1KTG3JHv+1Hk008vBq8KM9QDhN/kik014YBKaqogH8IC4uK8qHcXg7xJVJYXCKe+fR0rIKXFBINMs3eslGWaWImog/mwvVBIeJWeEFCrGbLeuzQLUv5eAcs5/BOGze+lNK0bghGOGy7+FRt+Y1QZeLFFnG2LUorHtKDRu0r5uKvkOQSwPON99MbD1ICszTKTx0uaLkkD5DNwQ+NgO8hvC0QhqsP1wd003cguWc40jFQl8ClTsjvNjMFjUFy3/eRPnHCiJTDiIMtHCR92B79Oyk6OqAOsvVX/Das3wryW9SdHuIdRFuPoySyh50YXFyy3pmBXNc5mHhGlQb/N7x6QH0Och13agkcau+Hd1/z9r099UVVQ94Oydu4vjEJoc1u8Df/kwMEdsITgnrn+2joUyey3QDhdtMcK4IH1mEIjsEA0et4/Ij7AxvLq3t88ok+V9gisvi9FXtQawxqk1+ioe6SXJfZZtgLfR9nzdmAePVhxqjQ1z0WW00OmM1qdawSK2vlvCKPL5RBIAUiz/h8V/UMPMrAAkU1f/ost75AsN7BbwlEppK+jXteZuW9al6sUX3JpQQCHxlnGP+bfn8I5699fvYCXZAoKsTAUc4PUb4eWdipxxs5RCDQiakMszUq8m4tCovZZK0WHgBUtJzfkZY/AWn3YxH26thG9Ve+MfpLbviPSeFzloDAl6HTkRw3VJ8JcPsSqtY+ZeA1VM8AL84Fm22K3dnHq4mUAyI3CRdi6jk9MgjTEAP/RPLgA0N5jzmGo4aenoapPDhYsrlsfsjCeUTvUTiec7ENm7EB6ExGuOVrA+pDgsxo3jwDLq1PKbrkt5dZA477cHUuf+CThnBIb0AuK8E3TT3hPp/p4RcFKuNqwUJPC5cnXrRdKPrsgx1Gv0UZzR7Y+GgkRpdYnXHGBPQ7sBMpkZFK7FJe9MBWHGEmbctNP68LUUxcxg1wymuK+CniIp7GvSfoXsa5n/Se6z3s0L2yeYsrgppz/oL4RzkZKGbbuD2b4M0ZcnczzDtIz8hFCtk5iUxVkTud7Bf4vDNtb6FXo5SvxbeN3dhArpI7dkNmHZW1LhqvJyJrzkujvTvVj9oX8xOuwyzZYXb0RZIw709yA0Oggc9tW8M0vx36tTDjAqPZopHusscvhStGEYwZEqgGA4h5zMvKOeJSmRzzcM5QP7F0hfgoI49aEbsc+Ie46NMDigYUWOnEx7vQVa5wfNxP6LGNwuJSRxTs484Gfu297dPRj62o4BU303lZtCQP6iXX2oKhMKC35omyyirlevC7YkNqG77JZK0nn9SgoudSviYqEl3Iir7LEG/XJvoSEMWP2DxTCj/2Wq85xe+6xX70q8eWfSDTRqG0THxLjcEhcIcn9pMFJWHiZkUVkK0ThATU1mFAGB0z+HTsJj0STv+lyxSSc69J9c0WgIE1sN9Nrucz+hWJRffQ+WA+uY9AlpLjHU9qX1AmlRNsD81RrGsYocT7UMUnKmYvYlbdcZRhcS/jupgt4AHuTqj3TGSUMt4T1L1lZA3cJ/g+pS2eTakYsQnEDoEzrg9tCPdbvYFJdsfg+KRgGXFWYkud9wdWF0OuPxb72dTn0EA8VtYbS+T10u1wL3f7SFkGhQwLunCpvh9P4ED8/s2WHAPRfKWOcJ3ERy47FfOncEOa6aM4I9WoFPEzCicdse9y/x65AoH4NlWfUIUMzhuMzuZa1RS0eT+U/O5ke6aSjE1S6Yfq8fX4cDdB69uWp7EfHcuu53SJYn7Mjlk3ke9IpvJ2b7ee6MoUPCci2MRJPWk0dLAjhfZfDHnLvoc3eo+LQomkCD84TQpuUCd/mADN6G6V+Il7Crc5kqCDTdRfbjl75k54+cuI/Lqr3A5H+PJFyoTJYPkp/DuY7eSiwjp15Zwspn2e91lrxKInPLWvEPBur8x99BY7VHqjknjDXmeeWupmcE/5k7LS8bLg6kfgwj/Z5ozbONcOtI9VDs5g51yXefJDSwU6cDSKABXAn/5FNLHEXKZA8eC9BE/knKbNZtzYO576tcj196jWw9CdJ++69Lstu0XgcXg7c5EWzviYj7JM3cStBEYn+w8epfABtsavsarQyi+vV6ZCTpyaxUAAiPl2n24kIIK2F5F2cYRIE5p9pTrV3Vii+Xo+nh6MC/d7Q7EPZgg2J+7AdmiEAkXGLhicLdbjjYFGVOrDSW33dPnZp5rSdRtJx3+y+lHHgFoo2mKzmLteQ7QsaNRvMtA2O0/9tz/1+2+7fiY6BBoANvJkxPKV5cH51hYBdbkHKwfthxJkVn10ePPDZqeeE42JDThvJxU7wnoGMpiQpe8+PwK3jI/SjpM2hV//ZC4GNR+dn6qtVPjavOkXtBfWExH67eyJaJaP83cAVSNEtPWQ/LGtdXMb4IOPr38o+YJgIu8EHs/2xQfJEA66OM1Hpr8gcVycnjPBo/sUPFGv+jn3alBKpfwWvrml5o6dO1lU3w7YrUv5x/Rk4M+v4X+G6xWp8n07LvEhDn74zBYhNudtwLoeHgclBf3l2ICSR4lccEHIPB819ZSMogbLOCWZCldPe9Vxje3LdHuSNv1tRiDofo+tGQL4Gav27hkx5cYBNlVoDvi5kpwnBWaEBXTNVHQ4NKW+0jjXuqHq3pLEjss4GqKBJO7mNidusT6cs3+Cjeh5OIvbiSda4p3BbD2071t7fHgOsSw/A83HojJR+HFEDH7TFwOr/zCyDrhStPXpCTT6evQ52TYmDW9ZdMB7wfvu1n0lOlkPYDfCL3gY0m2SXP1+VBwfWpNsSWnB0azEc+RAbsV1vlYsl+LIJ+g4mwpqSkINmvJjODg7kNl39zqxGwwKKod5To2bgN67eOg3PBPiWPDh1QeUDTQu1Tl0CFWvaD6wcm13S2MXd50J3Po5JhoF8k6laFI4H7uDYHtVRFtd/jSX9nS8Lkys7FYmk2N8cjZkLqEenCX/1E5Le9fX8kW1IfZRacKHMU3bG5QhDPiCrazR26NWgd49oTUWaVpFCzrF2FzkSSeMZ3BdYmabWmX7iS722067U7xf1yd79W9qXqDOtXLgNgP5PS5h7lY/ffJXe+s3GdPt/pgwYg+V1Yu19b3TxZfUFOSNPjTe/YFWtJxff7L14WV0wd5mIeqxkRoWr34MWEu99nfxL2V/JcEYOitE/dLCyNgTUzKWrTH6pG1au2K2QXRXmPgSA7VAHmrIgM9LW55zn55h7O1MW7FqeAXrWqL7jl3J5/168PajGukpbzE7jdOYZacLZWdHDI4Tc431+Tn6HV7c5zcxWbAPqO6t9HdfEA7P+bQUdyGs4p6zvQaWDTdyHU2L/AjIv6VxSsw4LTQcTtJXXeVjvobmLTaP1NToXnIvOOszxTq7APb0fFIQrfZvneFiOSQjnfp0GJ5dSooLiFoi7keVla6vgmuoAKgVFiZGj/VOt+Y2sSzP4HsKNY8/rOqTwycDDgzxCzrL71CATZtLl4ToAW9zYCPHxsH5HcEsbyCN4/NwOmAyUYgtOt5D3/30s+YgDVuqiYq8pg3bpHAZ8E/gAF+pMyI8ZQ72s/OEukRq3YufzWXN7PZ0bJtsf6Vz3w1bCdOaEco441NlaCOBxmmMuE9v8Wb3CA7RIT53Mdca44/c4m/k5vf2aw2fm8B+vMphhexP1ZUCoX6C+0EkwNSPy6b7+xLsyZY9/EThjjsQjMq31iD+s+sgVXpOa/PXIqi47WvZpP/Muqfw16Gv/1j35CJwDvKfayLyf6x7TjaEpg2C5Lb9Q7WrmRWT0MAn6vxOsvhaCQDnP7HQef7ZIAD8DF46N9STq40CEqzWihdDMiYDffr2mriuWAh5ddIyS+vSOy0lgSS5ynmnCsUZzhp/JhzCyJu5iZPrB7ZTxZMYpyb+lME7+LSrJQD1C1DEQx5jwbfYFEl+c2RPvDmeSZM6vli4zbjuMi5lSWQWN/G0XfKAoUSvG6f9DQlOodIIisUiGbBZgozfGvDvcp9xaoILPvne/u1CPWdVb1OwynxxV0MPTxG8rsvAKFLC0oHPX9VoA9vu/QCmt49yAhMoBfbnvBQ3/QwBNlN9Z9WfBpRYBnWrxQ2+vFuCQKMrf4LLgy1Xa55IkCR1BlvPrIfEGfkCwBieGavekhNcSVCfX715XQMWFBA/XrwiwWCjTnPADVbSFYbPIJ7sVyoNWLwkJ7rft2Og6GTWU8Nr/KJtm3MbX0lQwzvrlKzhTvusGT4AmyvFiAM4edYERx64CyWhu03Lt2T+uhvcewFF+y7YIBv2nlsca7SVUfkBViAJG7R8jRRqk8DRQ+35b2qUl3sdJp2At9HKCH3UYbBgaxChDE8YqCPBdWG2vZrdPT8fKUjnkcQi85HII8InGxTvp0RaNj9PDWnQ3QIRn0rvWqieMRLYBVVsrgadY3rmTeppARSRuHIInUHmPXF6TpBj8EVzh/SfBr1m0CtfNBEUnnvN/EM7j5jZPJheQaCE0WygqoA/EDLF9W0Sr921hfCW7wiarcSMqEsFvDA8QBSwURDXgHh/626IgoLBGYDhKvOLJvgOIIrb6eXYyawFjwsVeDO+PuKrg9qShyrW0sGczqVuDCI1ksWTq6ygeobYfg5OnlKdvtWRP4+po4ReD3fzMMkPpnuPMUAq0SjZ/ZikHX5zbzGX2nac8qhKtaSafaiLV8uTv+COSnnF3DP4fBlEfYTBgDZMc6Sp0Gh44KUGfU7vgNQfeb2tTAHIAuubqUh5JVXve+dfQz8Svss0NalSd4e/mg4hU9S8ccWHjPG91lQNm04/bdr1VKrbC3W/D6/Fg2hMubiJIrLXsa1cEDiBEQfeMLbLBd+Z+XK/4zNjgcMtIWWHB03NFLXAZyU9/CQ+JBZJVqx15D3cB6ySGQRP2loydJ4pIyEx13wN5KcutvPYN2s1OT4yAoXYoFqGm69IXyLLdvlkV5yu2oYXfvLTE9m27H0nv27M2MO5NsO1mWG7JBEt5W6zP4Zf1/iLpbX6vBiILdLpgiWPTEOL/p0nt4xhhAtkto18L39L1OD+ApFT6Kh/L5hsfugoUJXxWP2aya5GaghMDprO+H3km1fOtdsXu79E7mJ3qDnBoK4JMowA7rW20e2MACGS6oUlSDkX84+0ZaizfOSCCU5UES2MZeXbTM4BoOCeozPeiMrw2cpDSpcw/tPr32s5l+n+L/kv7/9oP/Z//Y8/18H/Ge3/z7+fbNnI/7rm9YB27jgBlEGZJZltQdlxw70EYfxyEKc4fNU602zwysdWGsKvSP33hhWlAc9HSaQPOW8C7UVRtPlG7Gou07wvr8Qi0A0JzKDu+U6Fj0cv3Ueprbd17AdTFUlUUgmeYdmc6AEVur/1C8HVzGIwRkU0C7WJ0CpLlOvT0ixxQ6iueoALZE8zHuVTwIt7fWUnrRqTkGpBafr69SgrWB3dFRuVeF8wT/75jkP2ougm6pz7bTGec8tYjClF/ciP/apLxNtuX4GUzwTqJ7NcKtRqr7WzDKJZq0APK+7omTIG/SMtWkqt4xYrH8po1APHyK5j4ydqXcI1YAtadkfvj93hFsiW5jlfa/pYZkb+vTseyJ/055uk+rRFwvHq/MYA//Rm7ccm4CURKIIHLK5zLAcmKdrP8iFo5Kb3t6kS7JcMCJ4n8XG0FPLma34znaX4LbzJf2TWlU4WXFzc2RLcNxfFd/wcqOt8HHQPdO6j3k+kKWj9yYD+WvnFGC7tM7mJcc1npafejWlQavWZmCZs/nwvL9Vw9IcO+HB3wN+W80+fb3SsixUSiU7uIZEO1USDnl9cLl3EuNhSUOTGlH5D4M5mgaII3Cy62ug1J4Y4qNgKPj2jqRZuj20udIIXMh0wfTINQH+8rj/Jwr0+X/BTIS3FgPMIKMPl4Hjojj4TFqYG5FSykLm/p4p4+esCkHABwxVO9uy7ubAvsBozv4+xKIU/OOS/B5mtRyV6uTIFNnDk4otMTz0IR76OTFJPJdr72ifXunGmSunTKIdQnYuGrCdyEpEepO+Uy/UWqqaDurQBERTFI168Xj5Mvqpfd/BEN3r6KXE11giFfGWmnm8Ew2aSDfhiq7AquuzZjB/BF9IliaUf1raP6w30fMidzvaTUCE7xyleFBnJ1CqX0r1sRzutJc4iyjNU8ZO6b/KJZ9VTb1Ovr/K+kcqx2+31NpjXmFjdOfiNFTuIM0A0DdnBwVlos4XNl/1GVeE65v3eP0jT1EKtPWO6YvcqaIHOxcAm6o8Ia8FeIy5iKUsjEkpdGhp29637is8XHuDRacdOQfPBM9bWE/LeexqcCO9LtriQ+lf6XpG/SfQualEYqiFW/l6cVtodGCWxfSmM6Lx/jT8snBAhC1Bsu7x0UMUP1/ZGq3PAGUuBhjvW3OURuidS+MMnyTL100lcglZGPyiQs2rv3rbW9RzzqsUwhOdvEDvtIV8eR2PI6+dZhSgpsKNfATDJUwkLMpa4ekeWnhlzPVwfWBDXGdj8WXr5ZbjhIxef6fPUn0fO0wH1dOW95YlmMX7Ip/USwN7G5YOjoFTx90BWsd3Zp1i8EBwuKtN8YQRevZk7Eb7vzWFyY4DifqqLLD3U6QcaXrQA4qw3QHnAcZIS05wvX/p1pmvjz70/Z4dG0cMLteeOsBG3TykSFpHc5xXFja/eeCsdpcSIKj556E/MgzNOX86KLwqYeQK88SmaSJFuvxmeGK2QNSifvjy8l2cF4lzEmErpOBLZn6/Y6BK8LuT5J0ebCVUuB7RfDnDHLgbmt/M/kxOlEPreZ5FFaUafPMJylTJlJfwiHde8yza9JrDii0KBQIzM/GLd3zYxZ8ZUr1jmu96jd1p6e4jaFaz52oLd1sCNqI+BMDm6SCg+dcK0pS352dm1zrO3EioD481KvDTNo4NvLO/ucAKoWTGnQplFzrhIXiLoyBQ3M5+sjsa6RTsI+74bUYxethCXlj2FAAFK7rya92e/SD5d6Qi6Pmt/UttThCELBEGY9OpMF+SUxOkWJx6dE08ncJqlLUudhmZVQE1szc97PKabGPVkSsJ5QK0jFfYZbh+n01h/NAI7M4y9H35AXuvaxrlUXcgTmT9fuVEsG6u7i/pG7yjqVyh5xIF546xX4TgcNo/cplN1li7LN9xTKxEvjFK+zkUrodusAKH9xW80FB6b25+EVDGL9nL38vanxO+W0oLMUCwZG3ngDJ2LoXD4si+vFvJ/uSVLLe8Yw5MyCSX4LT03I4l9/VVDn6nWhVwt5tmmDGazXL4nX2Fwy+u2CYZ11w1PqPmJbU/hfizB/s7vFlKSzyFtNqcwb+l68Y32nG/sxs30cpujPD21LPxushy/d+Wj8vbsTjkGvufHKH+Qxr+s+dNS5ZvjOQyqJWD5y7z+IqcH6M7XHFEyUE0WMcTz8qAcqmNUaLXObvoGDSDxjrYIWnhKbOe/8r7SYZlQb18VHu7gWv5NVthVWUz9veUjx+oPhAV+B0dP3rWJ0RHJd5PPU8iOwbwKg6C9ZWr0bJAyR2a+Z1cUJaadPptwdb22pFsGzFvlmOkLhF+9V6TR9RCmh6gEBDf9ESgrigrTKk3VmrKQPe2ovxs4uQBHueSFJI/WouywsHZXcJ3QcSetaD4jXdzwhX8TzqrpypSf15fha/MxY+IRoxDdBXLwNJWdPZu/rixUXal16blNuZ8sClMdU79zpSGoalV6pEufuD9s83qXiz8t5wdPu4dVlGmqI16+YwaWfDD9ksrh+Fxu2Vn9OBtfvmvzQ1Q1zVOL1962C/xlwrwk0WbfzFEoAFpB6TM/tNmHNYR1mppHc5XcDhqjiUh0CdrlhiUCT0DPP+DWDg9SOvdvcvE7z+gKE74RXft1UgNX+5m0Oiupou9FNs7wqGKFo/IibyYFPuatCGSVHCGII58QIedFHe+svkf2DeLO6zoKDcmo6VHZx37dV+iuFDjtlutqMEIP/xL8QQZM/EQ5LwMKSWC3JlGA39kEnXtp9+YvAqTzujcA6cseLX4Z/CCHeajgdEuVxpO8+Fqa+w2CkQdv4Rsze+CtQYpnaK6PppGKhfaqBZ8LT/298utAfIZ0wc/fsrSvDz3MT55IvtUHM6BBfXTK87YknesPECISo8V3xe9eyuD0tBKbbQFdvh91clH5VcBGcnENnktmEoIQtFGLpCNGMRIiv1LI/eoJBK+Uud0XpxHdHP4SZhIErOgUlikLgm96SOe7+Oq2vM6Atvi+c7MjOdq+vToIwzqSzV0cjOsS8vVEKjx8f8o7yROHcLMc6pntXCXPXn4WZFR/r85DrHWjt46UEX6dakXUL/yhARqIQMskXTTo/CN4KQ/pmtvoiVuD++Vouhex024yK/EGfiRnjNlpT+pXL5zDRODhUls0vuOZzIjDCdal+zJ6Qv2MNdEmrMr++XrW/vopVITt7GRjt/lnHkufcQmGKPe/Beq/0S//rr9Eq/wSJ+3Lpx1bOfopaY6xDXY9SqQBHUcRh0vbzR8fjb5FAyzaCzl2ulzEbPmnBJhnvh2UubOK1PvHcK/HCelTQtyxZLRu4iEtAAN9HNJ3f3w+UYwlwPR0/aaO+bYJ8fOWufiJFq8I21zk63R3+rFS4f3mfyIBJm+XZzhrx0lyfirFA3AgrwlGlUb7c9Uhr2So/Q19vMAf9RX6tEfUSgC3bwPWHMa1jqL0fuIujhgBYmEiJgEYKu43J8JKCiNQxAtRGAc0+UbphsuKuw6k2or6urFQtC06PQozwDvlTVdJtGSF+lNYSSWOuXR2CBRtv1h4SiHvX/8gF93UyYEnD9/spHF5D+PVwqXXZUHjz+RLaCeppt97OyB6pdgnReZLUClaGPrDR7QMRv4Vub6UNdS6SBGyj939Hh/S0oWOhl7BkldhqbjKS6tVkOASSINRhaBx3k9Ix4zCtF9K9kH7rozq7ZM9qbu4X5p73+8BJwo2jKalCv2Ex94xgjLIU83EtYFKev9g5rSVRw/vX46Rl+HAQbKO3kRSSPOx7NAg7iYPsSZW9iUhWWNJmntps9+ANYdYGqFPtblxodjjeQ2LqFJnUIGbOrCcV41EpA712pSXIztOtDAftRyyJssSr+rvJzDRuROqlEztbEAMZD3ADEHlMw1FmaeaaukWIawOJuS/lFNBUaWTljSf54ryMZJEm5AzO9x/rJaUv+a0n59GgCWmwfYRrwq/r3KsH0SE09RAo+7GuqB+8RRqcZ5MdWpItT77WJ2iSa4MSu46MGgEx94KIYDwVGC+bkkxU4pSzwdcXtCHByxFz0e2Pi9F+P7Qr/bz2I/s4OuDUKhRHS5FFn6IIPPid7sRYe8fBbuNVhzfTpGY8Kdl1zuMnOxllBf9++QpqmgRY4In6j3D2rwY44JfV6gjR4x1K/32GSC8LUlqJ8T3V5WetFCMHIGqC+fF4TUE02yaRP4vmgvz8tHekPHm4WDXd/KbcuvybIsnUiH3C+0/Yr6EdfNVfuovHTNPX/twT8jiT7/Y99Oqea1yaDP34MUvz/ARXm3h1M9wEfvbm0Hr6PbDfMdNeHCZKrd6kNvsgPYb+I6RtxTzftiFhhvokWBmNTtUQF+LVvNENc9y9WfV/emH85Dp98pk+5IanrlEAW/O4yotGJG+Hpawfqf5M9PuQHZtlGvJ5I7tfeToG2rUokp9pMC4mjC/2lypElaTSElj2KPur1z+zcTd4vM4apuceKL6EtgyPcM1WPBtCTQY9mh/NpWRGYBpZ9l7+97wirCCDcPMC6YOyFJzbEmtL4ziH6H10NneeEj56Y3A39JMERv0fj8WS4rWu5EbNfvBSODs2tddsp/PgnkPMFjUOSdUfp3P9yZd4ucIDDBm1oHYeR5N3lCmWWYOxNPnxKw8hPLhrMoi9TyJvxDvGhYdOijGgYQT5Sr5qnWju3uSvT9xiZj7oIeN5qQ6hWuD9hyxDQurlWQELyczs0vhu3riFLOMVirrvlLdrOA/NIL2ovxOElp4vmC80NFY70sBVeNMA+Vo7aNdHM/DW/pKtM2SAuplY+aM4r7h5E/kzIbE+yLCvbx0LX03NPY50jrR0m0AV/kAO9vJYmU/sWqe52Y0zsLchKnvj6+gvz6raYIc+I75UxqhaVEmQ9HErpWNbKPS2U7E7T5H8rCqq/ihgL3vljOVTHiz9fnXIpzYv7zOPeyB5//xr/84m6Kcntu/foCi9M3Q7GmR/jM/P+HsP7u6zYM/d7i+4KLir2U5qeA8X3yekt48/P389TqeeyhcNZ9nKbX+c5XsefA9/fXFder5X3h/lu/mP0t71PD8e+F8fvQi81cDBlV3kOf12mIq91/fdldz8ZPk1/Pur/Hsbt4Dw+nI/Xk7kAuxNx276rg6tiRXO1H1B/15XPT/Y3EQO3AO2H9+O8Pzyhs6s+4D/mrC39vf29/b39vf29/b39vf29/bP7cZ/AlcBwFAirLjE/x5SI2cVyg7XRw5vTWYvyR8IYkNfoagXLoHsD9/gSAiVqugVmsg2g0uqwVXCOnlX5eS+QBxgg+SSM/7vHnPMGdOxg4Y7XMMHrnM5vnr7a8pTD/Tm26T3y5DmC6DX+Ckuf46rf/PxeisT8fu/739t3/7vwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Cod = _t, Descricao = _t, Status = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Cod", type text}, {"Descricao", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

