table OrcamentoCompras
	lineageTag: e018ac09-cac1-41a0-bbd3-3b0e44abd4fa

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb09caf6-6605-471c-8e12-403cfdfd34f8
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column codigo
		dataType: string
		lineageTag: e31564b4-ca2f-4915-bce4-c5c996d3444f
		summarizeBy: none
		sourceColumn: codigo

		annotation SummarizationSetBy = Automatic

	column cod_canal
		dataType: string
		lineageTag: 25805d8b-7825-47dd-9dde-b49be1cd9aa5
		summarizeBy: none
		sourceColumn: cod_canal

		annotation SummarizationSetBy = Automatic

	column Orcamento
		dataType: double
		lineageTag: 2aaf14fa-e1a3-458e-958d-f59ede1cdce1
		summarizeBy: sum
		sourceColumn: Orcamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition OrcamentoCompras-76ec3f3b-6ab1-4b73-8672-9e2b3d42d62f = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Data = _t, cod_canal = _t, codigo = _t, Orcamento = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Data", type date}, {"Orcamento", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

