table Anunciante
	lineageTag: 13a9293c-7f1e-4f15-b2ee-c9a5046012b1

	column entId
		dataType: int64
		formatString: 0
		lineageTag: 4f71e52a-0de9-41db-b243-f953e1f14b51
		summarizeBy: none
		sourceColumn: entId

		annotation SummarizationSetBy = Automatic

	column Anunciante
		dataType: string
		lineageTag: 0f83d09d-b0d8-4e37-b256-c5dd17bffda0
		summarizeBy: none
		sourceColumn: Anunciante

		annotation SummarizationSetBy = Automatic

	partition Anunciante-05f4ec63-e93e-4ca0-9acc-25a0c1ea37a5 = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)    entidades.entNome,#(lf)    entidades.entId#(lf)From#(lf)    entidades"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"entNome", "Anunciante"}})
				in
				    #"Renamed Columns"

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Anunciante/Source.{entNome,0}","Section1/Anunciante/Source.{entId,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/Anunciante/Source.{entNome,0}","Section1/Anunciante/Source.{entId,1}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

