table Brands
	lineageTag: 61f6c9ff-5353-4882-ac13-a8fe889707d6

	column Id
		dataType: int64
		formatString: 0
		lineageTag: ab3da1ab-3a5e-45e9-8fe1-6a4302b9812e
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: a2188d7d-6b1b-488b-96d8-06022d523d79
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition Brands-12d10712-4d80-4705-bd13-307f98936f12 = m
		mode: import
		queryGroup: Share
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}, {"Id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

