table d_Neg_TaxaMultiProduto
	lineageTag: 7b5da83e-29b3-44cc-b520-9e35c0201871

	column negPerId
		dataType: int64
		formatString: 0
		lineageTag: 128e0b2e-8afd-4717-9f9e-f79faae6b2d0
		summarizeBy: none
		sourceColumn: negPerId

		annotation SummarizationSetBy = Automatic

	column multiProTaxa
		dataType: double
		lineageTag: 9cb79a67-50e6-4b3c-b016-29624378adcd
		summarizeBy: none
		sourceColumn: multiProTaxa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column multiProQuantidade
		dataType: int64
		formatString: 0
		lineageTag: 565988b6-853e-4195-8948-f9de5055e6c0
		summarizeBy: none
		sourceColumn: multiProQuantidade

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 5eb3ee85-a574-44cc-9828-62a04581c1b0
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition d_Neg_TaxaMultiProduto-71599c71-ade9-4ffe-b1ad-f114f9c8d4a6 = m
		mode: import
		queryGroup: Negociações
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)    negPeriodosTaxaMultiProduto.negPerId,#(lf)    negPeriodosTaxaMultiProduto.multiProTaxa,#(lf)    negPeriodosTaxaMultiProduto.multiProQuantidade#(lf)From#(lf)    negPeriodosTaxaMultiProduto"]),
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 0, 1, Int64.Type),
				    #"Filtered Rows" = Table.SelectRows(#"Added Index", each ([Index] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

