table Faturação
	lineageTag: fa78c712-6172-4c1c-8633-2902466405c1

	column data_doc_df
		dataType: dateTime
		formatString: Short Date
		lineageTag: 23276bc4-edd3-4201-9c58-959b18014cc0
		summarizeBy: none
		sourceColumn: data_doc_df

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column canCodigo
		dataType: int64
		formatString: 0
		lineageTag: 44e49768-1ba6-4a75-a241-41dd21645489
		summarizeBy: none
		sourceColumn: canCodigo

		annotation SummarizationSetBy = Automatic

	column tipPubId
		dataType: int64
		formatString: 0
		lineageTag: 2f1a87bd-bd2b-4f3b-9c7c-0a834d13e782
		summarizeBy: none
		sourceColumn: tipPubId

		annotation SummarizationSetBy = Automatic

	column codcliente_doc
		dataType: int64
		formatString: 0
		lineageTag: c7354840-71f4-4565-8ac8-0d53f46b9d42
		summarizeBy: sum
		sourceColumn: codcliente_doc

		annotation SummarizationSetBy = Automatic

	column anuncianteId
		dataType: int64
		formatString: 0
		lineageTag: bf68783f-8215-4bc8-b079-7132a49fedd8
		summarizeBy: none
		sourceColumn: anuncianteId

		annotation SummarizationSetBy = Automatic

	column distribuidorId
		dataType: int64
		formatString: 0
		lineageTag: 6ca72ee9-d3b2-4ff3-a0ba-7489d126d418
		summarizeBy: none
		sourceColumn: distribuidorId

		annotation SummarizationSetBy = Automatic

	column centralComprasId
		dataType: int64
		formatString: 0
		lineageTag: 76aa80fc-42b2-4806-a6b4-dcdf21ac7ca1
		summarizeBy: count
		sourceColumn: centralComprasId

		annotation SummarizationSetBy = Automatic

	column gruId
		dataType: int64
		formatString: 0
		lineageTag: 2ea2d462-c3f3-41b1-a066-2df4bbfe983b
		summarizeBy: count
		sourceColumn: gruId

		annotation SummarizationSetBy = Automatic

	column executivoId
		dataType: int64
		formatString: 0
		lineageTag: 55f13996-6e99-4905-abe6-f64a3c8048e7
		summarizeBy: count
		sourceColumn: executivoId

		annotation SummarizationSetBy = Automatic

	column valorFaturado
		dataType: double
		lineageTag: c4daf3ea-ae9c-4f12-b244-d6f5c0387d5d
		summarizeBy: sum
		sourceColumn: valorFaturado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordPubCodigo
		dataType: int64
		formatString: 0
		lineageTag: b88ecee5-ec16-43e5-87ed-48fc9b9a24a3
		summarizeBy: sum
		sourceColumn: ordPubCodigo

		annotation SummarizationSetBy = Automatic

	column proId
		dataType: int64
		formatString: 0
		lineageTag: 08bb99ef-944f-44ae-9454-491106d1857f
		summarizeBy: none
		sourceColumn: proId

		annotation SummarizationSetBy = Automatic

	column vendedorId
		dataType: int64
		formatString: 0
		lineageTag: f19eef61-49bc-4b9b-8fe1-9ce9ee1af987
		summarizeBy: none
		sourceColumn: vendedorId

		annotation SummarizationSetBy = Automatic

	column ordPubFlagValorBrutoVendas
		dataType: int64
		formatString: 0
		lineageTag: 89511434-d0bc-4921-bec9-85a5852994ba
		summarizeBy: none
		sourceColumn: ordPubFlagValorBrutoVendas

		annotation SummarizationSetBy = Automatic

	column data_emissao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6a631db0-ec16-4138-b874-9de260fa53df
		summarizeBy: none
		sourceColumn: data_emissao

		variation Variation
			isDefault
			relationship: edf5fb51-a1c7-48b1-9726-99d308e64e11
			defaultHierarchy: LocalDateTable_202571d0-8c17-419a-b101-4f7e8d669940.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column data_venc
		dataType: dateTime
		formatString: General Date
		lineageTag: b699b274-a194-4286-94d4-9427732215a7
		summarizeBy: none
		sourceColumn: data_venc

		variation Variation
			isDefault
			relationship: b4caebc5-3fab-4992-bb6f-7825023a2a94
			defaultHierarchy: LocalDateTable_08c6cf5d-373a-4f47-83ce-6f7d7595bb04.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column descricao
		dataType: string
		lineageTag: 679e4abb-7652-4c0a-9cb3-5a8d1db2b33b
		summarizeBy: none
		sourceColumn: descricao

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: 53e22855-489b-4ba4-b687-66833b7f287a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column totalFaturado
		dataType: double
		lineageTag: 5019b818-49d1-4c99-8c07-076e2a14c1b0
		summarizeBy: sum
		sourceColumn: totalFaturado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valorFact
		dataType: double
		lineageTag: 95160837-074f-49a7-ab27-a39b901b3096
		summarizeBy: sum
		sourceColumn: valorFact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordPubAno
		dataType: int64
		formatString: 0
		lineageTag: 6e666129-44cb-48f6-a0f3-0390cc7ab33a
		summarizeBy: sum
		sourceColumn: ordPubAno

		annotation SummarizationSetBy = Automatic

	column ordPubMes
		dataType: int64
		formatString: 0
		lineageTag: 20c5be7a-5cce-41c5-abf6-6ac088efc5b6
		summarizeBy: sum
		sourceColumn: ordPubMes

		annotation SummarizationSetBy = Automatic

	column Data_Correcao
		dataType: dateTime
		formatString: Short Date
		lineageTag: be3682c8-4374-41d6-b2a5-0879ac216e56
		summarizeBy: none
		sourceColumn: Data_Correcao

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column negPerTipo
		dataType: string
		lineageTag: a8ddb6c2-ee9f-4875-b96f-d7da4e12ac34
		summarizeBy: none
		sourceColumn: negPerTipo

		annotation SummarizationSetBy = Automatic

	column pacId
		dataType: int64
		formatString: 0
		lineageTag: ccf2b35e-ea47-4dc1-b6c5-c15b74deb869
		summarizeBy: none
		sourceColumn: pacId

		annotation SummarizationSetBy = Automatic

	hierarchy 'data_doc_df Hierarchy'
		lineageTag: cb0261c6-7eed-4535-ae44-304a1f280aca

		level data_doc_df
			lineageTag: edb432b7-14ab-495a-bc77-e698bb84eeff
			column: data_doc_df

	partition Faturação-9c98843f-674d-4e2f-ad2e-df6a114475a1 = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				    Source = Sql.Database(ServerP, BD, [Query="Select#(lf)    doc_factura_pub.ordPubCodigo,#(lf)    Doc_Factura.data_doc_df,#(lf)    ordemPub.ordPubAno,#(lf)    ordemPub.ordPubMes,#(lf)    doc_factura_pub.canCodigo,#(lf)    doc_factura_pub.tipPubId,#(lf)    Doc_Factura.codcliente_doc,#(lf)    doc_factura_pub.anuncianteId,#(lf)    doc_factura_pub.distribuidorId,#(lf)    doc_factura_pub.proId,#(lf)    doc_factura_pub.vendedorId,#(lf)    ordemPub.ordPubFlagValorBrutoVendas,#(lf)#(tab)pacotes.pacId,#(lf)    IsNull(doc_factura_pub.centralComprasId, campanhas.camCentralCompras) As centralComprasId,#(lf)    IsNull(doc_factura_pub.gruId, campanhas.camGrupoId) As gruId,#(lf)    IsNull(doc_factura_pub.vendedorId, campanhas.camVendedor) As executivoId,#(lf)    Case#(lf)        When t_documento.movimento = 'D'#(lf)        Then 1#(lf)        Else -1#(lf)    End * doc_factura_pub.ordPubValor As valorFaturado,#(lf)    Doc_Factura.data_emissao,#(lf)    Doc_Factura.data_venc,#(lf)    t_documento.descricao,#(lf)    Case#(lf)        When (Year(Doc_Factura.data_doc_df) <> ordemPub.ordPubAno Or Month(Doc_Factura.data_doc_df) <> ordemPub.ordPubMes) or ( t_documento.descricao = 'Nota Crédito Pub')#(lf)        Then 'CORREÇÃO'#(lf)        Else ''#(lf)    End,#(lf)    vTotalFact.totalFaturado,#(lf)    ordemPub.valorFact,#(lf)    Case ordemPub.ordPubFlagFixo#(lf)        When 2#(lf)        Then negPeriodos.negPerTipo#(lf)        When 1#(lf)        Then 'V'#(lf)        Else 'D'#(lf)    End As negPerTipo#(lf)#(tab)#(lf)From#(lf)    doc_factura_pub #(lf)#(tab)Join Doc_Factura On Doc_Factura.id_factura = doc_factura_pub.id_factura #(lf)#(tab)Join t_documento On t_documento.codigo = Doc_Factura.tipo_doc #(lf)#(tab)Join ordemPub On ordemPub.ordPubCodigo = doc_factura_pub.ordPubCodigo #(lf)#(tab)Left Outer Join negPeriodos With(NoLock) On negPeriodos.negPerId = ordemPub.ordPubNegociacao #(lf)#(tab)Join campanhas On campanhas.camId = ordemPub.camId #(lf)#(tab)Left Join Pacotes With(NoLock) On ordempub.pacId = pacotes.pacId#(lf)#(tab)Join#(lf)    (Select#(lf)         doc_factura_pub.ordPubCodigo,#(lf)         Sum(Case#(lf)             When t_documento.movimento = 'D'#(lf)             Then 1#(lf)             Else -1#(lf)         End * doc_factura_pub.ordPubValor) As totalFaturado#(lf)     From#(lf)         doc_factura_pub Join#(lf)         Doc_Factura On Doc_Factura.id_factura = doc_factura_pub.id_factura#(lf)                 And Doc_Factura.estado_doc <> 'A' Join#(lf)         t_documento On t_documento.codigo = Doc_Factura.tipo_doc#(lf)     Group By#(lf)         doc_factura_pub.ordPubCodigo) vTotalFact On vTotalFact.ordPubCodigo = doc_factura_pub.ordPubCodigo#(lf)Where#(lf)    Doc_Factura.estado_doc <> 'A' And#(lf)    Year(Doc_Factura.data_doc_df) >= Year(GetDate()) - 5"]),
				    #"Inserted Merged Column" = Table.AddColumn(Source, "Data_Correcao", each Text.Combine({"1/", Text.From([ordPubMes], "pt-PT"), "/", Text.From([ordPubAno], "pt-PT")}), type text),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Merged Column",{{"Data_Correcao", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

