table MediaAgencies
	lineageTag: e1cc252b-0e08-473a-8395-ff97e1f27fb8

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b6ab082a-28a1-4766-8912-f10e7a9e7445
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Central =
			
			
			SWITCH(
			    TRUE()
			        , ISERROR ( FIND ( "DIRECTOS", [Ag. Meios] ) ) <> TRUE (), "CLIENTES DIRETOS",
			        ISERROR ( FIND ( "CARAT", [Ag. Meios] ) ) <> TRUE (), "POWER MEDIA",
			        ISERROR ( FIND ( "ARENA", [Ag. Meios] ) ) <> TRUE (), "HAVAS",
			        ISERROR ( FIND ( "OMD", [Ag. Meios] ) ) <> TRUE (), "OMG",
			        ISERROR ( FIND ( "INITIATIVE", [Ag. Meios] ) ) <> TRUE (), "MEGA",
			        ISERROR ( FIND ( "WAVEMAKER", [Ag. Meios] ) ) <> TRUE (), "GRUPO M",
			        ISERROR ( FIND ( "STARCOM", [Ag. Meios] ) ) <> TRUE (), "MEGA",
			        ISERROR ( FIND ( "MINDSHARE", [Ag. Meios] ) ) <> TRUE (), "GRUPO M",
			        ISERROR ( FIND ( "PHD", [Ag. Meios] ) ) <> TRUE (), "OMG",
			        ISERROR ( FIND ( "MEDIACOM", [Ag. Meios] ) ) <> TRUE (), "GRUPO M",
			        ISERROR ( FIND ( "GROUPM", [Ag. Meios] ) ) <> TRUE (), "GRUPO M",
			        ISERROR ( FIND ( "HAVAS", [Ag. Meios] ) ) <> TRUE (), "HAVAS",
			        ISERROR ( FIND ( "MCCANN", [Ag. Meios] ) ) <> TRUE (), "MEGA",
			        ISERROR ( FIND ( "ZENITH", [Ag. Meios] ) ) <> TRUE (), "MEGA",
			        ISERROR ( FIND ( "STUDIOM", [Ag. Meios] ) ) <> TRUE (), "GRUPO M",
			        ISERROR ( FIND ( "EXPRESSAO", [Ag. Meios] ) ) <> TRUE (), "POWER MEDIA",
			        ISERROR ( FIND ( "MEDIAGATE", [Ag. Meios] ) ) <> TRUE (), "POWER MEDIA",
			        ISERROR ( FIND ( "INDEFINIDO", [Ag. Meios] ) ) <> TRUE (), "INDEFINIDO"
			    , "OUTROS"
			)
		lineageTag: 68908b44-7e6a-49fa-943a-dacc70383eb3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ag. Meios'
		dataType: string
		lineageTag: fcde9e53-8ccd-4d17-827a-33a49a62259d
		summarizeBy: none
		sourceColumn: Ag. Meios

		annotation SummarizationSetBy = Automatic

	partition MediaAgencies-840bf8b2-0bb7-4fe6-a127-605c0cf788dd = m
		mode: import
		queryGroup: Share
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Ag. Meios" = _t, ID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Ag. Meios", type text}, {"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

