table Sectors
	lineageTag: c3c31a1e-39f3-4857-a576-31c304f1ca26

	column Id
		dataType: int64
		formatString: 0
		lineageTag: fb42a307-07ca-427e-b9f9-2d17414f0e55
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: ebc32d16-21ea-4857-9cd8-3d1d82606686
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	partition Sectors-779bed8b-dad3-4d07-9e04-1c7179ee6d3d = m
		mode: import
		queryGroup: Share
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sector = _t, Id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sector", type text}, {"Id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

