table Targets
	lineageTag: b86000a1-7c71-453f-a878-c2fa1443abab

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 94ff4ef1-51b9-4fb9-8f3d-ea64b90bc40d
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column GRP
		dataType: string
		lineageTag: 5aaa1970-dcad-438e-a7c0-68d24bee81a3
		summarizeBy: none
		sourceColumn: GRP

		annotation SummarizationSetBy = Automatic

	partition Targets-02d731c0-a200-40dd-b9fb-03183044f087 = m
		mode: import
		queryGroup: Share
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [GRP = _t, Id = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"GRP", type text}, {"Id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

