table TipoProduto
	lineageTag: be3ebb4e-cc89-4b9d-9a24-44ac31b4a856

	column tipProId
		dataType: string
		lineageTag: 2846bd6e-8810-4eba-bb18-82cd27db6568
		summarizeBy: none
		sourceColumn: tipProId

		annotation SummarizationSetBy = Automatic

	column 'Setor Atividade'
		dataType: string
		lineageTag: c17dd88e-a8b3-488d-9516-8e60e9b65b03
		summarizeBy: none
		sourceColumn: Setor Atividade

		annotation SummarizationSetBy = Automatic

	column Sub-Setor
		dataType: string
		lineageTag: c77d2d51-95cc-4ea7-ba8e-1a17bac0bd4f
		summarizeBy: none
		sourceColumn: Sub-Setor

		annotation SummarizationSetBy = Automatic

	column SubSub-Setor
		dataType: string
		lineageTag: 1f6926af-8f67-4eb4-a619-87596e8505a4
		summarizeBy: none
		sourceColumn: SubSub-Setor

		annotation SummarizationSetBy = Automatic

	partition TipoProduto-95bed59c-9690-4462-bb0f-dc4c1222a6b7 = m
		mode: import
		queryGroup: Encomendas
		source =
				let
				Source = Sql.Database(ServerP, BD, [Query="select#(lf)    isnull(tp3.tipProId,isnull(tp2.tipProId, tp1.tipProId)) as tipProId,#(lf)    ltrim(rtrim(tp1.tipProdescricao)) as tipProNivel1,#(lf)    ltrim(rtrim(tp2.tipProdescricao)) as tipProNivel2,#(lf)    ltrim(rtrim(tp3.tipProdescricao)) as tipProNivel3#(lf)from tipoProduto tp1#(lf)    left outer join tipoProduto tp2 on tp2.tipProPaiId=tp1.tipProId#(lf)    left outer join tipoProduto tp3 on tp3.tipProPaiId=tp2.tipProId#(lf)where#(lf)    tp1.tipProPaiId is null#(lf)#(lf)#(lf)#(lf)union all#(lf)#(lf)#(lf)#(lf)select#(lf)    tp1.tipProId as tipProId,#(lf)    ltrim(rtrim(tp1.tipProdescricao)) as tipProNivel1,#(lf)    NULL as tipProNivel2,#(lf)    NULL as tipProNivel3#(lf)from tipoProduto tp1#(lf)where#(lf)    tp1.tipProPaiId is null#(lf)    --and tp1.tipProdescricao like '%COMERCIO%'#(lf)    and tp1.tipProId in (select tipPropaiid from tipoProduto)#(lf)#(lf)#(lf)#(lf)union all#(lf)#(lf)#(lf)#(lf)select#(lf)    tp2.tipProId as tipProId,#(lf)    ltrim(rtrim(tp1.tipProdescricao)) as tipProNivel1,#(lf)    ltrim(rtrim(tp2.tipProdescricao)) as tipProNivel2,#(lf)    NULL as tipProNivel3#(lf)from tipoProduto tp1#(lf)    left outer join tipoProduto tp2 on tp2.tipProPaiId=tp1.tipProId#(lf)where#(lf)    tp1.tipProPaiId is null#(lf)    and tp2.tipProId in (select tipPropaiid from tipoProduto)#(lf)#(lf)#(lf)#(lf)order by 1"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"tipProNivel1", "Setor Atividade"}, {"tipProNivel2", "Sub-Setor"}, {"tipProNivel3", "SubSub-Setor"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

