table Executivos
	lineageTag: 7966c825-c0fd-45cb-a3fc-9de29514c951

	column Executivo
		dataType: string
		lineageTag: 6eb460b2-399d-4970-b0e0-75716a619252
		summarizeBy: none
		sourceColumn: Executivo

		annotation SummarizationSetBy = Automatic

	column ExecutivoCodigo
		dataType: string
		lineageTag: 3711350b-3abb-4180-a1ea-22ee19222377
		summarizeBy: none
		sourceColumn: ExecutivoCodigo

		annotation SummarizationSetBy = Automatic

	partition Executivos-96d9685a-a092-4441-9212-1e5005b3ea4b = m
		mode: import
		queryGroup: CORE
		source =
				// let
				//     Source = Sql.Database(Org, BD, [Query="Select#(lf)    [User].Name Executivo,#(lf)    [User].ExternalCode ExecutivoCodigo#(lf)From#(lf)    [User]"]),
				//     #"Filtered Rows" = Table.SelectRows(Source, each ([ExecutivoCodigo] <> null))
				// in
				//     #"Filtered Rows"
				
				let
				    SQL = "SELECT
				            [User].Name AS Executivo,
				            [User].ExternalCode AS ExecutivoCodigo
				        FROM [User]
				        WHERE 1 = 1
				            AND [User].ExternalCode IS NOT NULL",
				    Source = Sql.Database(Org, BD, [Query = SQL]),
				    Verificar = let
				        Agrupar = Table.Group(Source, {"ExecutivoCodigo"}, {"Contagem", each Table.RowCount(_), Int64.Type})
				        in Table.SelectRows(Agrupar, each [Contagem] > 1)[ExecutivoCodigo],
				    #"Registros Duplicados" = Table.SelectRows(Source, each List.Contains(Verificar, [ExecutivoCodigo])),
				    #"Filtrar Sem Duplicidade" = Table.SelectRows(Source, each not ([ExecutivoCodigo] = "BVENA" and [Executivo] = "Bruna Kethelyn Candida Venancio"))
				in
				    #"Filtrar Sem Duplicidade"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

