table GrupoAgencia
	lineageTag: 742cb6ec-692f-40ca-8f81-2ba4175763a6

	column GrupoAgencia
		dataType: string
		lineageTag: 0142fa10-ef1f-477b-81a2-3448c7d80352
		summarizeBy: none
		sourceColumn: GrupoAgencia

		annotation SummarizationSetBy = Automatic

	column Agencia
		dataType: string
		lineageTag: 7a041042-e124-4d2d-9663-90e30a7e681d
		summarizeBy: none
		sourceColumn: Agencia

		annotation SummarizationSetBy = Automatic

	column AgenciaCodigo
		dataType: string
		lineageTag: 0358c369-3196-496b-8c67-514eed10b407
		summarizeBy: none
		sourceColumn: AgenciaCodigo

		annotation SummarizationSetBy = Automatic

	column GrupoAgenciaCodigo
		dataType: string
		lineageTag: e969f7ab-67d6-41d3-8f66-0ec45c308bbd
		summarizeBy: none
		sourceColumn: GrupoAgenciaCodigo

		annotation SummarizationSetBy = Automatic

	column Grupo_Agencia
		dataType: string
		lineageTag: c712dd38-0cd5-4716-940a-1fa602f96c84
		summarizeBy: none
		sourceColumn: Grupo_Agencia

		annotation SummarizationSetBy = Automatic

	partition GrupoAgencia-9ed82b92-d56c-481e-9c8b-39c29ea39b08 = m
		mode: import
		queryGroup: CORE
		source = ```
				// let
				//     Source = Sql.Database(Org, BD, [Query="Select#(lf)    TRIM(union1.Agencia) As Agencia,#(lf)    TRIM(union1.GrupoAgencia) As GrupoAgencia,#(lf)    TRIM(union1.AgenciaCodigo) As AgenciaCodigo,#(lf)    TRIM(union1.GrupoAgenciaCodigo) As GrupoAgenciaCodigo,#(lf)    TRIM(union1.GrupoAgencia) + ' (' + TRIM(union1.GrupoAgenciaCodigo) + ')' AS Grupo_Agencia#(lf)From#(lf)    ((Select#(lf)         cl.Name As Agencia,#(lf)         g.Name As GrupoAgencia,#(lf)         cl.ExternalCode As AgenciaCodigo,#(lf)         g.ExternalCode As GrupoAgenciaCodigo#(lf)     From#(lf)         Entity cl Inner Join#(lf)         Entity g On cl.ExternalCode = g.ExternalCode#(lf)                 And cl.ParentID Is Null Inner Join#(lf)         EntityEntityType On g.ID = EntityEntityType.EntityID#(lf)     Where#(lf)         EntityEntityType.EntityTypeID = 2)#(lf)     Union#(lf)     (Select#(lf)         cl.Name As Agencia,#(lf)         g.Name As GrupoAgencia,#(lf)         cl.ExternalCode As AgenciaCodigo,#(lf)         g.ExternalCode As GrupoAgenciaCodigo#(lf)     From#(lf)         Entity cl Inner Join#(lf)         Entity g On cl.ParentID = g.ID Inner Join#(lf)         EntityEntityType On g.ID = EntityEntityType.EntityID#(lf)     Where#(lf)         EntityEntityType.EntityTypeID = 2)) As union1"]),
				//     #"Uppercased Text" = Table.TransformColumns(Source,{{"AgenciaCodigo", Text.Upper, type text}}),
				//     #"Removed Duplicates" = Table.Distinct(#"Uppercased Text", {"AgenciaCodigo"})
				// in
				//     #"Removed Duplicates"
				
				let
				    SQL = "WITH
				        GrupoPorExternalCode AS (
				            SELECT
				                cl.Name AS Agencia,
				                g.Name AS GrupoAgencia,
				                cl.ExternalCode AS AgenciaCodigo,
				                g.ExternalCode AS GrupoAgenciaCodigo
				            FROM
				                Entity cl
				                INNER JOIN Entity g
				                    ON cl.ExternalCode = g.ExternalCode
				                    AND cl.ParentID IS NULL
				                INNER JOIN EntityEntityType
				                    ON g.ID = EntityEntityType.EntityID
				            WHERE
				                EntityEntityType.EntityTypeID = 2
				        ),
				
				        GrupoPorParentId AS (
				            SELECT
				                cl.Name AS Agencia,
				                g.Name AS GrupoAgencia,
				                cl.ExternalCode AS AgenciaCodigo,
				                g.ExternalCode AS GrupoAgenciaCodigo
				            FROM
				                Entity cl
				                INNER JOIN Entity g
				                    ON cl.ParentID = g.ID
				                INNER JOIN EntityEntityType
				                    ON g.ID = EntityEntityType.EntityID
				            WHERE
				                EntityEntityType.EntityTypeID = 2
				        ),
				
				        Union1 AS (
				            SELECT
				                Agencia,
				                GrupoAgencia,
				                AgenciaCodigo,
				                GrupoAgenciaCodigo
				            FROM
				                GrupoPorExternalCode
				
				        UNION
				
				            SELECT
				                Agencia,
				                GrupoAgencia,
				                AgenciaCodigo,
				                GrupoAgenciaCodigo
				            FROM
				                GrupoPorParentId
				        )
				        
				    SELECT
				        TRIM(Union1.Agencia) AS Agencia,
				        TRIM(Union1.GrupoAgencia) AS GrupoAgencia,
				        UPPER(TRIM(Union1.AgenciaCodigo)) AS AgenciaCodigo,
				        TRIM(Union1.GrupoAgenciaCodigo) AS GrupoAgenciaCodigo,
				        TRIM(Union1.GrupoAgencia) + ' (' + TRIM(Union1.GrupoAgenciaCodigo) + ')' AS Grupo_Agencia
				    FROM
				        Union1",
				    Source = Sql.Database(Org, BD, [Query = SQL])
				in
				    Source
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

