table PosicaoCarteira
	isHidden
	lineageTag: 0826d2be-e49c-4cdd-a5f3-0992427f950c

	column Cliente
		dataType: string
		isHidden
		lineageTag: 6f077ac4-fb7e-420d-b0d0-1d89613cf93f
		summarizeBy: none
		sourceColumn: Cliente

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClienteCodigo
		dataType: string
		isHidden
		lineageTag: e76c7a8c-ce0c-44bd-a795-ab4281e9baa7
		summarizeBy: none
		sourceColumn: ClienteCodigo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Agencia
		dataType: string
		isHidden
		lineageTag: 7c34370c-eacd-4d6d-a238-da44aa0bd22a
		summarizeBy: none
		sourceColumn: Agencia

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgenciaCodigo
		dataType: string
		isHidden
		lineageTag: a4d1335c-3541-43e3-b1f0-8374fe9e591e
		summarizeBy: none
		sourceColumn: AgenciaCodigo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Executivo
		dataType: string
		isHidden
		lineageTag: 91f08da8-727e-4592-8b56-70f854568eb8
		summarizeBy: none
		sourceColumn: Executivo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ExecutivoCodigo
		dataType: string
		isHidden
		lineageTag: 1c3d767a-188e-45b9-880e-fb30ae30022e
		summarizeBy: none
		sourceColumn: ExecutivoCodigo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DataInicio
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: 6555fbb3-b3f3-4dd6-87b5-150ca2a1f4b3
		summarizeBy: none
		sourceColumn: DataInicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DataFim
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: cfb8f0d9-74aa-49fe-a3dd-11750ab00c47
		summarizeBy: none
		sourceColumn: DataFim

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Mes Inicio'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4c72a725-5bff-4e22-89f9-91b32f34b65a
		summarizeBy: none
		sourceColumn: Mes Inicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mes Nome Inicio'
		dataType: string
		isHidden
		lineageTag: d86cc3bc-7e19-4709-941c-ec006cd0ce32
		summarizeBy: none
		sourceColumn: Mes Nome Inicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ano Inicio'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6b947c0a-e9b7-4920-94db-196ed3e1db3a
		summarizeBy: none
		sourceColumn: Ano Inicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mes Fim'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b5110538-ef83-4532-aa74-758601cd7095
		summarizeBy: none
		sourceColumn: Mes Fim

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmpVendaCodigo
		dataType: string
		isHidden
		lineageTag: 855f2cd0-0ac6-4bc7-a2bf-6e98dc26d110
		summarizeBy: none
		sourceColumn: EmpVendaCodigo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmpresaVenda
		dataType: string
		isHidden
		lineageTag: 812c900c-b797-4d93-8a2c-d9aee7a1c762
		summarizeBy: none
		sourceColumn: EmpresaVenda

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmpVenda
		dataType: string
		isHidden
		lineageTag: ab80f248-f0a0-4702-8069-8a0f6081cb12
		summarizeBy: none
		sourceColumn: EmpVenda

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EndFim
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 300b6682-646c-46c1-a09a-33479ccbe281
		summarizeBy: none
		sourceColumn: EndFim

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartInicio
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: db3e73dd-eeaf-4b07-a9ef-ee511a4a2d17
		summarizeBy: none
		sourceColumn: StartInicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientesDiretos = IF.EAGER( PosicaoCarteira[Cliente] = PosicaoCarteira[Agencia], "CLIENTES DIRETOS", "COM AGÊNCIAS" )
		isHidden
		lineageTag: 56a27702-1f69-471b-bbfb-e382d3219d57
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estado = IF( PosicaoCarteira[DataFim] >= TODAY(), "Ativa", "Inativa" )
		isHidden
		lineageTag: 5e31df94-9c26-4202-b78e-17bab14c14dc
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c3eab4fc-e00b-420d-a09e-9c7222274a36
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Fim' =
			
			IF( year(PosicaoCarteira[DataFim]) = 2099, BLANK(), PosicaoCarteira[DataFim] )
		formatString: dd/mm/yyyy
		lineageTag: 98ffd3b3-9235-45e7-a159-4e885477e52f
		summarizeBy: none

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Status
		dataType: string
		lineageTag: 3e7078f1-7297-444a-8b6a-928a50824624
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column codIntegrador
		dataType: string
		lineageTag: 1a37715f-5620-4403-9d37-53a158356705
		summarizeBy: none
		sourceColumn: codIntegrador

		annotation SummarizationSetBy = Automatic

	partition PosicaoCarteira-fddb36b0-92bc-41ca-89e1-ea614118b435 = m
		mode: import
		queryGroup: Carteira
		source =
				let
				    SQL = "WITH Base AS (
				            SELECT
				                [User].Name AS Executivo,
				                [User].ExternalCode AS ExecutivoCodigo,
				                ENTITYCLIENT.Name AS Cliente,
				                ENTITYCLIENT.ExternalCode AS ClienteCodigo,
				                ENTITYAGENCY.Name AS Agencia,
				                ENTITYAGENCY.ExternalCode AS AgenciaCodigo,
				                CustomerPortfolio.BeginDate AS DataInicio,
				                COALESCE(CustomerPortfolio.EndDate, DATEFROMPARTS(YEAR(GETDATE()) + 5, 12, 31)) AS DataFim,
				                Company.ExternalCode AS EmpVendaCodigo,
				                Company.Name AS EmpVenda,
				                CONCAT(Company.ExternalCode, ' - ', Company.Name) AS EmpresaVenda,
				                CustomerPortfolio.ID,
				                UPPER(ENTITYCLIENT.ExternalCode + ENTITYAGENCY.ExternalCode) AS codIntegrador,
				                CASE WHEN CustomerPortfolio.Status = 1 THEN 'Sim' ELSE 'Não' END AS Status
				            FROM CustomerPortfolio
				            LEFT JOIN [User]
				                ON [User].ID = CustomerPortfolio.UserID
				            LEFT JOIN Entity ENTITYAGENCY
				                ON ENTITYAGENCY.ID = CustomerPortfolio.EntityAgencyID
				            LEFT JOIN Entity ENTITYCLIENT
				                ON ENTITYCLIENT.ID = CustomerPortfolio.EntityClientID
				            LEFT JOIN Company
				                ON CustomerPortfolio.CompanyID = Company.ID
				        )
				        SELECT
				            Base.Executivo,
				            Base.ExecutivoCodigo,
				            Base.Cliente,
				            Base.ClienteCodigo,
				            Base.Agencia,
				            Base.AgenciaCodigo,
				            Base.DataInicio,
				            Base.DataFim,
				            Base.EmpVendaCodigo,
				            Base.EmpVenda,
				            Base.EmpresaVenda,
				            Base.ID,
				            Base.codIntegrador,
				            Base.Status,
				            MONTH(Base.DataInicio) AS [Mes Inicio],
				            YEAR(Base.DataInicio)  AS [Ano Inicio],
				            MONTH(Base.DataFim)    AS [Mes Fim],
				            DATEFROMPARTS(YEAR(Base.DataInicio), MONTH(Base.DataInicio), 1) AS StartInicio,
				            EOMONTH(Base.DataFim) AS EndFim
				        FROM Base",
				    Source = Sql.Database(Org, BD, [Query = SQL]),
				    // Só o nome do mês fica no Power Query: depende da cultura do modelo, não da do servidor
				    #"Inserted Coluns" = Table.AddColumn(Source, "Mes Nome Inicio", each Date.MonthName([DataInicio]), type text)
				in
				    #"Inserted Coluns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

