table TipoMidia
	lineageTag: a1ed728a-2b4b-45d3-a46c-97747d893d35

	column ID
		dataType: int64
		formatString: 0
		lineageTag: cd32f759-5e4b-4df2-8906-39ab87d0d6b1
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column BusinessUnitID
		dataType: int64
		formatString: 0
		lineageTag: 21474c8a-6413-4f1f-b848-b8e483274044
		summarizeBy: count
		sourceColumn: BusinessUnitID

		annotation SummarizationSetBy = Automatic

	column ExternalCode
		dataType: string
		lineageTag: 530a16eb-128f-438f-bdd5-53158495f5c1
		summarizeBy: none
		sourceColumn: ExternalCode

		annotation SummarizationSetBy = Automatic

	column TipoMidia
		dataType: string
		lineageTag: 6f6f6ffc-9e30-4956-a6f6-2b79b614c8a6
		summarizeBy: none
		sourceColumn: TipoMidia

		annotation SummarizationSetBy = Automatic

	partition TipoMidia-c6435eba-39c9-4870-9b1f-71e4c66cfcff = m
		mode: import
		queryGroup: Carteira
		source =
				// let
				//     Source = Sql.Database(Org, BD, [Query="Select#(lf) *#(lf)FROM#(lf)ForecastMediaType"]),
				//     #"Uppercased Text" = Table.TransformColumns(Source,{{"ExternalCode", Text.Upper, type text}}),
				//     #"Renamed Columns" = Table.RenameColumns(#"Uppercased Text",{{"Name", "TipoMidia"}})
				// in
				//     #"Renamed Columns"
				
				let
				    SQL = "Select
				            ID
				            , BusinessUnitID
				            , UPPER(ExternalCode) AS ExternalCode
				            , Name AS TipoMidia
				        FROM ForecastMediaType",
				    Source = Sql.Database(Org, BD, [Query = SQL])
				in
				    Source

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

